# When apps report XDG_CURRENT_DESKTOP=sway:wlroots, portal still prefers wlr for capture.
[preferred]
default=wlr;gtk;
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
