#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Linux" ]; then

  DIR=$HOME/.config/yadm/bootstrap.d/

  if [[ -d $DIR ]]; then
    /usr/bin/run-parts --verbose --regex=".*" "$DIR"
  fi
fi
